NotFound: Not found
InvalidTopic: You supplied invalid topic parameters, please try again.
TopicOwner name@Text: By #{name}
TopicAuthor name@Text: Updated by: #{name}
UpdateTopic: Update topic
CreateTopic: Create topic
EditThisTopic: Edit This Topic
TopicCreated title@Text: Your topic "#{title}" has been created.
TopicUpdated: Your topic has been updated.
MapCreated title@Text: Your map "#{title}" has been created.
CreateMap: Create map
UpdateMap: Update map
MapUpdated: Your map has been updated.
LabelsUpdated: Labels have been updated.

LabelName: Label name

InvalidJsonInput json@Text: Invalid JSON input (#{json})

NotYourMap: You cannot edit another user's map.

UpdateSettings: Update settings
SettingsUpdated: Your settings have been updated.

YourHandle: User handle
HandleTooltip: Short name to identify you on the site.
YourEmail: Email Address
EmailTooltip: Your email will never be shared. It is only used for Gravatar.
YourUrl: Website
YourBio: Short bio

MapForBlog: Map to post
Slug: Slug
SlugTooltip: Unique name for URLs
InvalidBlogInfo: Invalid blog information, please try again.
InvalidBookInfo: Invalid book information, please try again.

YourName: Your name
Title: Title
Format: Format
Content: Content
Summary: Summary

UploadDitaZip: DITA ZIP File
DitaMapUploaded: Your DITA content has been uploaded.

BookMap: Map
BookMapTooltip: This map contains all the content for the book.
BookTopic: Topic
BookTopicTooltip: A brief introduction section displayed before the Table of Contents.

Chunking: Chunking level
ChunkingTooltip: Determines how many levels deep the TOC will descend.

MapTitleTooltip: Name of the entire map.

SelectedContent: Selected content
AvailableTopics: Available topics

TopicsListHeading: Topics
MapsListHeading: Maps

Edit: Edit

PageName: Page name
PageTopic: Redirected topic

BrowseFilter: Filter

PleaseLogIn: Please log in to gain access to all features of the site.
LoggedInAs name@Text: Logged in as #{name}
Logout: Logout
NotLoggedIn: Not logged in.
LoginNow: Login now

YouAreHere: You are here:

AddBlogPost: Add blog post
AddBook: Add book

# Page titles
LoginTitle: Login
CreateTopicTitle: Create Topic
TopicTitle title@Text: #{title}
SettingsTitle: Settings
CreateMapTitle: Create Map
EditMapTitle title@Text: Edit Map "#{title}"
MapListTitle: Map List
ShowMapTitle title@Text: #{title}
ShowMapTopicTitle maptitle@Text topictitle@Text: #{maptitle} :: #{topictitle}
LabelsTitle: Labels
BrowseTitle: Browse
BlogPostTitle title@Text: #{title}
HomepageTitle: Homepage
BookTitle title@Text: #{title}
BookChapterTitle title@Text: #{title}
