NotFound: Not found
InvalidTopic: You supplied invalid topic parameters, please try again.
TopicOwner name@Text: By #{name}
TopicAuthor name@Text: Updated by: #{name}
UpdateTopic: Update topic
CreateTopic: Create topic
EditThisTopic: Edit This Topic
TopicCreated title@Text: Your topic "#{title}" has been created.
TopicUpdated: Your topic has been updated.
MapCreated title@Text: Your map "#{title}" has been created.
CreateMap: Create map

UpdateSettings: Update settings
SettingsUpdated: Your settings have been updated.

YourName: Your name
Title: Title
Format: Format
Content: Content
Summary: Summary

MapTitleTooltip: Name of the entire map.

# Page titles
CreateTopicTitle: Create Topic
HomepageTitle: Homepage
TopicTitle title@Text: #{title}
SettingsTitle: Settings
CreateMapTitle: Create Map
EditMapTitle title@Text: Edit Map "#{title}"
