NotFound: Not found
InvalidTopic: You supplied invalid topic parameters, please try again.
TopicOwner name@Text: By #{name}
TopicAuthor name@Text: Updated by: #{name}
UpdateTopic: Update topic
CreateTopic: Create topic
EditThisTopic: Edit This Topic
TopicCreated title@Text: Your topic "#{title}" has been created.
TopicUpdated: Your topic has been updated.
MapCreated title@Text: Your map "#{title}" has been created.
CreateMap: Create map
UpdateMap: Update map
MapUpdated: Your map has been updated.

InvalidJsonInput: Invalid JSON input

NotYourMap: You cannot edit another user's map.

UpdateSettings: Update settings
SettingsUpdated: Your settings have been updated.

YourName: Your name
Title: Title
Format: Format
Content: Content
Summary: Summary

MapTitleTooltip: Name of the entire map.

SelectedContent: Selected content
AvailableTopics: Available topics

TopicsListHeading: Topics
MapsListHeading: Maps

Edit: Edit

PageName: Page name
PageTopic: Redirected topic

# Page titles
CreateTopicTitle: Create Topic
TopicTitle title@Text: #{title}
SettingsTitle: Settings
CreateMapTitle: Create Map
EditMapTitle title@Text: Edit Map "#{title}"
MapListTitle: Map List
ShowMapTitle title@Text: #{title}
ShowMapTopicTitle maptitle@Text topictitle@Text: #{maptitle} :: #{topictitle}
